import crypto from "node:crypto";
import type { NextFunction, Request, Response } from "express";
import { config } from "../config.js";
import { ForbiddenError } from "../shared/errors.js";

const CSRF_COOKIE = "uprise_csrf";
const unsafeMethods = new Set(["POST", "PUT", "PATCH", "DELETE"]);

export function createCsrfToken(req: Request, res: Response) {
  // Generate a signed token using HMAC
  const randomBytes = crypto.randomBytes(16).toString("hex");
  const signature = crypto.createHmac("sha256", config.jwtAccessSecret).update(randomBytes).digest("hex");
  const token = `${randomBytes}.${signature}`;

  const isProd = config.nodeEnv === "production";
  const isSecure = req.secure || req.headers?.["x-forwarded-proto"] === "https" || isProd;

  res.cookie(CSRF_COOKIE, token, {
    httpOnly: false,
    sameSite: isSecure ? "none" : "lax",
    secure: isSecure,
    maxAge: 1000 * 60 * 60 * 4
  });

  res.json({
    success: true,
    data: { csrfToken: token },
    requestId: req.id
  });
}

export function csrfProtection(req: Request, _res: Response, next: NextFunction) {
  if (!unsafeMethods.has(req.method)) {
    return next();
  }

  const cookieToken = req.cookies?.[CSRF_COOKIE] as string | undefined;
  const headerToken = req.headers["x-csrf-token"] as string | undefined;

  if (!headerToken) {
    return next(new ForbiddenError("CSRF validation failed."));
  }

  // 1. Verify token signature to ensure it was legitimately generated by our server
  const [randomBytes, signature] = headerToken.split(".");
  if (!randomBytes || !signature) {
    return next(new ForbiddenError("CSRF validation failed."));
  }

  const expectedSignature = crypto.createHmac("sha256", config.jwtAccessSecret).update(randomBytes).digest("hex");

  const isSignatureValid = crypto.timingSafeEqual(Buffer.from(signature, "hex"), Buffer.from(expectedSignature, "hex"));

  if (!isSignatureValid) {
    return next(new ForbiddenError("CSRF validation failed."));
  }

  // 2. If cookie token is present (double-submit verification), ensure they match
  if (cookieToken) {
    const cookieBuf = Buffer.from(cookieToken);
    const headerBuf = Buffer.from(headerToken);
    if (cookieBuf.length !== headerBuf.length || !crypto.timingSafeEqual(cookieBuf, headerBuf)) {
      return next(new ForbiddenError("CSRF validation failed."));
    }
  }

  return next();
}
